env: prod # test, dev, prod, docker

logging:
  level: info

PprofServer:
  host: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: masterdb

replica_database:
  host: localhost
  port: 5433
  user_to_replicate: userepo
  password_to_replicate: 12345
  dbname: replica_db
